---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  "/api/v1/invoices":
    post:
      summary: Create invoice
      tags:
      - Invoices
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token
        schema:
          type: string
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '422':
          description: validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: object
                  properties:
                    invoice_uuid:
                      type: string
                      format: uuid
                    status:
                      type: string
                    emitter_name:
                      type: string
                    emitter_rfc:
                      type: string
                    receiver_name:
                      type: string
                    receiver_rfc:
                      type: string
                    amount_cents:
                      type: integer
                    amount_currency:
                      type: string
                    emitted_at:
                      type: string
                      format: date
                    expires_at:
                      type: string
                      format: date
                    signed_at:
                      type: string
                      format: date
                    cfdi_digital_stamp:
                      type: string
                  required:
                  - invoice_uuid
                  - status
                  - emitter_name
                  - emitter_rfc
                  - receiver_name
                  - receiver_rfc
                  - amount_cents
                  - amount_currency
                  - emitted_at
              required:
              - invoice
    get:
      summary: List invoices
      tags:
      - Invoices
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
  "/api/v1/invoices/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show invoice
      tags:
      - Invoices
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token
        schema:
          type: string
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
    patch:
      summary: Update invoice
      tags:
      - Invoices
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token
        schema:
          type: string
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
        '422':
          description: validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: object
                  properties:
                    status:
                      type: string
    delete:
      summary: Delete invoice
      tags:
      - Invoices
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token
        schema:
          type: string
      responses:
        '204':
          description: no content
        '401':
          description: unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://rails-assessment-a3-gtovar-76f03123ca1f.herokuapp.com
